# Generated by Django 2.2 on 2022-11-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='product',
        ),
        migrations.AddField(
            model_name='contractitem',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contracts_api.Contract'),
        ),
    ]
