# Generated by Django 2.2 on 2022-11-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contracts_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractitem',
            name='contract_id',
        ),
    ]
